//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeEvent.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public string PurchaserId { get; set; }
        public int CategoryId { get; set; }
        public int TicketStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TicketCategories TicketCategories { get; set; }
    }
}
